project:
  type: website

website:
  title: "Caritas Schweiz Reporting"
  navbar:
    logo: ./logo.png
    left:
      - href: index.qmd
        text: Home
      - market.qmd
      - map.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



