project:
  type: website

website:
  title: "Caritas Schweiz Reporting"
  navbar:
    logo: ./logo.png
    left:
      - href: index.qmd
        text: Home
      - market.qmd
      - map.qmd
      - about.qmd
      - text: "Kunden"
        menu:
          - href: clients.qmd
            text: Kundenübersicht Allgemein
          - href: clients_2022.qmd
            text: Kunden 2022
          - href: clients_2023.qmd
            text: Kunden 2023

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



