project:
  type: website

website:
  title: "Caritas Schweiz Reporting"
  navbar:
    logo: ./logo.png
    left:
      - href: index.qmd
        text: Home
      - href: market.qmd
        text: Markt
      - href: map.qmd
        text: Karte
      - href: clients.qmd
        text: "Kunden"
  sidebar:
    - title: "Kunden"
      style: "docked"
      background: light
      contents:
        - clients.qmd
        - clients-2022.qmd
        - clients-2023.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



