project:
  type: website

website:
  title: "Caritas Schweiz Reporting"
  search:
    location: navbar
    type: overlay
  navbar:
    logo: ./logo.png
    left:
      - href: index.qmd
        text: Home
      - href: market.qmd
        text: Markt
      - href: map.qmd
        text: Karte
      - href: clients.qmd
        text: Kunden
      - href: cases.qmd
        text: Falldaten
  sidebar:
    - title: "Kunden"
      style: "docked"
      background: light
      contents:
        - clients.qmd
        - clients-2022.qmd
        - clients-2023.qmd
    - title: "Falldaten"
      style: "docked"
      background: light
      contents:
        - cases.qmd
        - cases-need.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



